### PR TITLE
Rewrite the whole thing!

### PR DESCRIPTION
**Pull request by rokclimb15**
Rewritten for a 2 day coding project I undertook. Some features:
- Python3 compatibility
- Parser uses regex
- Iterable parser and result filter
- Split components into modules/classes for non-CLI parsing
- Filtering options
- Updated README with usage
- Sample files for tests

### CODE REVIEW

**Comment by ivuk** [comment]
Thanks for the contribution, I really appreciate it!

I'll try to look at it during this weekend, at a first glance it looks great. :)

**Comment by ivuk** [comment]
Hi @rokclimb15, could you please let me know if the `summary` flag works for you? I've tried it in some combinations, but it seems to fail for me:
```python
Traceback (most recent call last):
  File "./ufp.py", line 6, in <module>
    cli.execute()
  File "/dev/shm/ufp/src/ufp/cli.py", line 165, in execute
    formatter.format()
  File "/dev/shm/ufp/src/ufp/formatter/summary.py", line 54, in format
    sorted(self.src_ports)]) + '\n\n')
TypeError: '<' not supported between instances of 'str' and 'int'
```
I'm guessing that the `sorted` call is getting a set which contains a list of integers, so it fails to concatenate the string properly.

Also, could you please let me know whether you've tested any higher logging levels? I've tried it with i.e. `sudo ufw logging high`, but since the parser doesn't know about the AUDIT log messages, it fails to run. If it's OK with you, we could solve this by simply ignoring the AUDIT messages for now, with something like:
```python
diff --git a/src/ufp/parser/base.py b/src/ufp/parser/base.py
index 9aa5d7b..47bb129 100644
--- a/src/ufp/parser/base.py
+++ b/src/ufp/parser/base.py
@@ -35,6 +35,8 @@ class ParsedLine():
             self.action = self.ACTION_ALLOW
         elif action == 'BLOCK':
             self.action = self.ACTION_BLOCK
+        elif action == 'AUDIT':
+            pass
         else:
             raise ValueError("action must be ALLOW or BLOCK")
```
Please let me know what you think. Thanks again for this pull request, seems like you've put a lot of work into this! :)

**Comment by rokclimb15** [comment]
Hey @ivuk thanks for testing this!

I understand the problem with the `summary` flag. It was a late change that I added to accommodate multicast and other ip types that don't have a port. I'll figure out something else that's int sortable like 0 and add a test.

I have not tested it with an audit log. I like your suggestion for now, so I'll add that and a test for it tomorrow.

**Comment by rokclimb15** [comment]
@ivuk this is ready for re-review.

**Comment by ivuk** [comment]
Looks good to me now, there might be some minor output alignment things (i.e. I think there's a missing tab character in `-src2dst` output formatter), but that's all minor.

I haven't tested everything completely, but what I've looked at seems very cool.

I can merge this as is, there's just one minor nitpick left; how do you feel about cleaning out the `__pycache__` directories before I merge this? It seems to me it might be a bit nicer if we don't carry them in the repository.

Let me know what you think, I can remove that after the merge is done if you'd prefer it done that way.

Thanks for the work you've put into this so far, I really appreciate it! :)

**Comment by rokclimb15** [comment]
I am absolutely 100% in favor of removing `__pycache__` dirs. The only problem is, I don't see any! `__pycache__` is in .gitignore and I don't see any in my repo. Where do you see them?

**Comment by ivuk** [comment]
Argh, sorry, that was my mistake, that `__pycache__` is on my machine. :/

I'll merge this as-is now, thanks for the great work!

**Comment by rokclimb15** [comment]
Thanks Igor!

**Pull request merged**
